### ISSUE TITLE
Brendan

### ISSUE THREAD

**Issue by Codevendor** [brendanashworth/inferjs#1]
Just wondering if your using this npm package name inferjs. I have created a large project called InferJS. I would like to use the npm name. Here is my project  https://github.com/Codevendor/inferjs

Since you have no dependents for your code and haven't updated anything, only one initial commit, could be possible to remove your npm package and release the name. Would you be willing to do that for me?

I'll add you to my Acknowledgments in my readme.

Thanks,
Adam

**Comment by brendanashworth** [comment]
Sure you can have it, what's your npm username?

**Comment by Codevendor** [comment]
Thank you so much.

My username on npm is: codevendor

What link do you want me to acknowledge you with in my readme?

**Comment by brendanashworth** [comment]
@Codevendor I added you as a maintainer

If you wanted to acknowledge me, you can always drop a link to my startup, https://buntinglabs.com 😄 otherwise don't worry about it
